GroceryProject/GroceryProject/Models/Food.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GroceryProject.Models
{
    public class Food
    {
        public int FoodID { get; set; }
        public string FoodName { get; set; }
        public double FoodPrice { get; set; }
        public string FoodDescription { get; set; }
        public int FoodStock { get; set; }
        public string FoodImage { get; set; }
        public bool FoodStatus { get; set; } = true;
        public int CategoryID { get; set; } // Bir yiyeceğin sadece bir kategorisi olabilir.
        public virtual Category Category { get; set; }
    }
}

GroceryProject/GroceryProject/Controllers/FoodController.cs
using GroceryProject.Models;
using GroceryProject.Repositories;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace GroceryProject.Controllers
{
    public class FoodController : Controller
    {
        Context db = new Context();
        FoodRepository foodRepository = new FoodRepository();
        private readonly IWebHostEnvironment _webHostEnvironment;

        public FoodController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View(foodRepository.TList("Category"));
        }
        [HttpGet]
        public IActionResult AddFood()
        {
            List<SelectListItem> values = (from x in db.Categories.Where(x => x.CategoryStatus == true).ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CategoryName,
                                               Value = x.CategoryID.ToString()
                                           }).ToList();
            ViewBag.vls = values;
            return View();
        }
        [HttpPost]
        public IActionResult AddFood(Food p, IFormFile FoodImage)
        {

            if (!ModelState.IsValid)
            {
                List<SelectListItem> values = (from x in db.Categories.ToList()
                                               select new SelectListItem
                                               {
                                                   Text = x.CategoryName,
                                                   Value = x.CategoryID.ToString()
                                               }).ToList();
                ViewBag.vls = values;

                var messages = ModelState.ToList();
                return View("AddFood");
            }

            if (FoodImage != null && FoodImage.Length > 0)
            {
                string uniqueFileName = Guid.NewGuid().ToString() + "_" + FoodImage.FileName;
                string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", uniqueFileName);
                using (var stream = new FileStream(imagePath, FileMode.Create))
                {
                    FoodImage.CopyTo(stream);
                }
                p.FoodImage = uniqueFileName;
            }

            foodRepository.TAdd(p);
            return RedirectToAction("Index");
        }
        public IActionResult GetFood(int id)
        {
            List<SelectListItem> values = (from x in db.Categories.Where(x => x.CategoryStatus == true).ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CategoryName,
                                               Value = x.CategoryID.ToString()
                                           }).ToList();
            ViewBag.vls = values;

            var y = foodRepository.TGet(id);
            Food fd = new Food()
            {
                FoodName = y.FoodName,
                FoodDescription = y.FoodDescription,
                FoodPrice = y.FoodPrice,
                FoodStock = y.FoodStock,
                FoodID = y.FoodID,
                CategoryID = y.CategoryID
            };
            return View(fd);
        }
        [HttpPost]
        public IActionResult UpdateFood(Food p, IFormFile FoodImage)
        {
            if (FoodImage != null && FoodImage.Length > 0)
            {
                string uniqueFileName = Guid.NewGuid().ToString() + "_" + FoodImage.FileName;
                string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", uniqueFileName);
                using (var stream = new FileStream(imagePath, FileMode.Create))
                {
                    FoodImage.CopyTo(stream);
                }

                // Yiyeceğin resim yolu
                p.FoodImage = uniqueFileName;
            }
            var x = foodRepository.TGet(p.FoodID);
            x.FoodID = p.FoodID;
            x.FoodName = p.FoodName;
            x.FoodDescription = p.FoodDescription;
            x.FoodImage = p.FoodImage;
            x.FoodPrice = p.FoodPrice;
            x.FoodStock = p.FoodStock;
            x.CategoryID = p.CategoryID;
            foodRepository.TUpdate(x);

            return RedirectToAction("Index");
        }
        public IActionResult DeleteFood(int id)
        {
            var x = foodRepository.TGet(id);
            x.FoodStatus = false;
            foodRepository.TUpdate(x);
            return RedirectToAction("Index");
        }
    }
}

GroceryProject/GroceryProject/Views/Food/AddFood.cshtml
@model GroceryProject.Models.Food
@{
    ViewData["Title"] = "AddFood";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Add Food</h2>
<br />

<form class="form-group" asp-action="AddFood" asp-controller="Food" method="post" enctype="multipart/form-data">
    @Html.LabelFor(x => x.FoodName, "Food Name")
    @Html.TextBoxFor(x => x.FoodName, new { @class = "form-control" })
    <span asp-validation-for="FoodName" class="text-danger"></span>
    <br />
    @Html.LabelFor(x => x.FoodDescription, "Food Description")
    @Html.TextAreaFor(x => x.FoodDescription, new { @class = "form-control" })
    <span asp-validation-for="FoodDescription" class="text-danger"></span>
    <br />
    @Html.LabelFor(x => x.CategoryID, "Category")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vls, new { @class = "form-control" })
    <span asp-validation-for="CategoryID" class="text-danger"></span>
    <br />
    @Html.LabelFor(x => x.FoodPrice, "Food Price")
    @Html.TextBoxFor(x => x.FoodPrice, new { @class = "form-control" })
    <span asp-validation-for="FoodPrice" class="text-danger"></span>
    <br />
    @Html.LabelFor(x => x.FoodStock, "Food Stock")
    @Html.TextBoxFor(x => x.FoodStock, new { @class = "form-control" })
    <span asp-validation-for="FoodStock" class="text-danger"></span>
    <br />
    @Html.LabelFor(x => x.FoodImage, "Food Image")
    <input type="file" name="FoodImage" required="" />
    @*<span asp-validation-for="FoodImage" class="text-danger"></span>*@
    <br />
    <button class="btn btn-success">Save</button>
</form>

GroceryProject/GroceryProject/Views/Food/GetFood.cshtml
@model GroceryProject.Models.Food
@{
    ViewData["Title"] = "GetFood";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<h2>Update Food</h2>
<br />
<form class="form-group" asp-action="UpdateFood" asp-controller="Food" method="post" enctype="multipart/form-data">
    @Html.LabelFor(x => x.FoodID, "Food ID")
    @Html.TextBoxFor(x => x.FoodID, new { @class = "form-control", @readonly = "readonly" })
    <br />
    @Html.LabelFor(x => x.FoodName, "Food Name")
    @Html.TextBoxFor(x => x.FoodName, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.FoodDescription, "Food Description")
    @Html.TextBoxFor(x => x.FoodDescription, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Category.CategoryID, "Category Name")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vls, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.FoodPrice, "Food Price")
    @Html.TextBoxFor(x => x.FoodPrice, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.FoodStock, "Food Stock")
    @Html.TextBoxFor(x => x.FoodStock, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.FoodImage, "Food Image")
    <input type="file" name="FoodImage" />
    <br />
    <button class="btn btn-success">Save</button>
</form>

GroceryProject/GroceryProject/Views/Food/Index.cshtml
@model List<GroceryProject.Models.Food>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Foods</h2>
<br />
<table id="table1" class="table table-bordered">
    <thead>
        <tr>
            <th>Food ID</th>
            <th>Food Name</th>
            <th>Description</th>
            <th>Category Name</th>
            <th>Price</th>
            <th>Stock</th>
            <th>Operations</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model.Where(x => x.FoodStatus == true))
        {
            <tr>
                <td>@x.FoodID</td>
                <td>@x.FoodName</td>
                <td>@x.FoodDescription</td>
                <td>@x.Category.CategoryName</td>
                <td>@x.FoodPrice</td>
                <td>@x.FoodStock</td>
                <td>
                    <a href="/Food/GetFood/@x.FoodID" class="btn btn-warning">Update</a>
                    @Html.ActionLink("Delete", "DeleteFood", new { id = x.FoodID }, new { @class = "btn btn-danger", onclick = "return confirm('Are You Sure?')" })
                </td>
            </tr>
        }
    </tbody>
</table>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet" />
<script>
    $('#table1').DataTable();
</script>

<br />
<a href="/Food/AddFood/" class="btn btn-primary">Add Food</a>