GroceryProject/GroceryProject/Models/Chart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GroceryProject.Models
{
    public class Chart
    {
        public string ProductName { get; set; }
        public int ProductStock { get; set; }
    }
}

GroceryProject/GroceryProject/Controllers/ChartController.cs
using GroceryProject.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GroceryProject.Controllers
{
    public class ChartController : Controller
    {
        Context db = new Context();
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Index2()
        {
            return View();
        }
        public IActionResult VisualizeProductResult()
        {
            return Json(ProductList());
        }
        public List<Chart> ProductList()
        {
            List<Chart> cs = new List<Chart>();
            using (var c = new Context())
            {
                cs = c.Foods.Where(y => y.FoodStatus == true).Select(x => new Chart
                {
                    ProductName = x.FoodName,
                    ProductStock = x.FoodStock
                }).ToList();
            }
            return cs;
        }
        public IActionResult Statistics()
        {
            var value1 = db.Foods.Where(x => x.FoodStatus == true).Count();
            ViewBag.v1 = value1;

            var value2 = db.Foods.Where(x => x.FoodStatus == true).Sum(x => x.FoodStock);
            ViewBag.v2 = value2;

            var value3 = db.Foods.Where(z => z.FoodStatus == true).OrderByDescending(x => x.FoodStock).Select(y => y.FoodName).FirstOrDefault();
            ViewBag.v3 = value3;

            var value4 = db.Foods.Where(z => z.FoodStatus == true).OrderBy(x => x.FoodStock).Select(y => y.FoodName).FirstOrDefault();
            ViewBag.v4 = value4;

            var value5 = db.Foods.Where(x=> x.FoodStatus == true && x.CategoryID == 2).Count();
            ViewBag.v5 = value5;

            var value6 = db.Foods.Where(x => x.FoodStatus == true && x.CategoryID == 1 ).Count();
            ViewBag.v6 = value6;

            var value7 = db.Foods.Where(x => x.FoodStatus == true && x.CategoryID== 3).Count();
            ViewBag.v7 = value7;

            var value8 = db.Foods.Where(x => x.FoodStatus == true && x.CategoryID == 4).Count();
            ViewBag.v8 = value8;

            var value9 = db.Foods.Average(x => x.FoodPrice).ToString("0.00");
            ViewBag.v9 = value9;

            var value10 = db.Foods.Where(z => z.FoodStatus == true).OrderByDescending(x => x.FoodPrice).Select(y => y.FoodName).FirstOrDefault();
            ViewBag.v10 = value10;

            return View();
        }
    }
}

GroceryProject/GroceryProject/Views/Chart/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stocks');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.productName, obj.productStock]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Food - Stock Pie Chart",
                width: 1000,
                height: 600,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>

GroceryProject/GroceryProject/Views/Chart/Index2.cshtml
@{
    ViewData["Title"] = "Index2";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stocks');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.productName, obj.productStock]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Food - Stock Column Chart",
                width: 1000,
                height: 600,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.ColumnChart(document
                .getElementById('ColumnChart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="ColumnChart_div"></div>
</body>
</html>

GroceryProject/GroceryProject/Views/Chart/Statistics.cshtml
@{
    ViewData["Title"] = "Statistics";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Statistics</h2>
<br />
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>

    <!-- Custom Theme files -->
    <link href="~/web2/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Custom Theme files -->
    <script src="~/web2/js/jquery.min.js"></script>
    <link rel="stylesheet" href="~/web2/css/font-awesome.css">
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Metro Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--webfont-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <link href="~/web2/css/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />


    <script src="~/web2/js/easyResponsiveTabs.js" type="text/javascript"></script>

    <script src="~/web2/js/main.js"></script> <!-- Resource jQuery -->
    <!-- chart -->
    <script src="~/web2/js/Chart1.js"></script>
    <!-- //chart -->
</head>
<body>
    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#1abc9c">
                <div class="icon-text">
                    <h3>@ViewBag.v1</h3>
                    <p>Total Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#2ecc71">

                <div class="icon-text">
                    <h3>@ViewBag.v2</h3>
                    <p>Sum Stock</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#3498db">

                <div class="icon-text">
                    <h3>@ViewBag.v3</h3>
                    <p>Max Stock Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#9b59b6">

                <div class="icon-text">
                    <h3>@ViewBag.v4</h3>
                    <p>Min Stock Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#16a085">
                <div class="icon-text">
                    <h3>@ViewBag.v5</h3>
                    <p>Fruit Count</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#27ae60">

                <div class="icon-text">
                    <h3>@ViewBag.v6</h3>
                    <p>Vegetables Count</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#2980b9">

                <div class="icon-text">
                    <h3>@ViewBag.v7</h3>
                    <p>Legumes Count</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#8e44ad">

                <div class="icon-text">
                    <h3>@ViewBag.v8</h3>
                    <p>Snacks Count</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#f1c40f">
                <div class="icon-text">
                    <h3>@ViewBag.v9</h3>
                    <p>Average Food Price</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#e67e22">

                <div class="icon-text">
                    <h3>@ViewBag.v10</h3>
                    <p>Max Price Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            @*<div class="orders" style="background-color:#e74c3c">

                    <div class="icon-text">
                        <h3>@ViewBag.d10</h3>
                        <p>Buzdolabı Sayısı</p>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="visitors" style="background-color:#95a5a6">

                    <div class="icon-text">
                        <h3>@ViewBag.d11</h3>
                        <p>Laptop Sayısı</p>
                    </div>
                    <div class="clearfix"></div>
                </div>*@
            <div class="clearfix"></div>
        </div>
    </div>
</body>
</html>