GroceryProject/GroceryProject/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GroceryProject.Models
{
    public class Category
    {
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDescription { get; set; }
        public bool CategoryStatus { get; set; } = true;
        public List<Food> Foods { get; set; } // Bir kategori birden fazla yiyecek barındırabilir.
    }
}

GroceryProject/GroceryProject/Controllers/CategoryController.cs
using GroceryProject.Models;
using GroceryProject.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GroceryProject.Controllers
{
    public class CategoryController : Controller
    {
        Context db = new Context();
        CategoryRepository categoryRepository = new CategoryRepository();
        public IActionResult Index()
        {
            return View(categoryRepository.TList());
        }
        [HttpGet]
        public IActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddCategory(Category p)
        {
            if (!ModelState.IsValid)
            {
                var messages = ModelState.ToList();
                return View("AddCategory");
            }
            categoryRepository.TAdd(p);
            return RedirectToAction("Index");
        }
        public IActionResult GetCategory(int id)
        {
            var x = categoryRepository.TGet(id);
            Category ct = new Category()
            {
                CategoryID = x.CategoryID,
                CategoryName = x.CategoryName,
                CategoryDescription = x.CategoryDescription
            };
            return View(ct);
        }
        [HttpPost]
        public IActionResult UpdateCategory(Category p)
        {
            var x = categoryRepository.TGet(p.CategoryID);
            x.CategoryName = p.CategoryName;
            x.CategoryDescription = p.CategoryDescription;
            x.CategoryStatus = true;
            categoryRepository.TUpdate(x);
            return RedirectToAction("Index");
        }
        public IActionResult DeleteCategory(int id)
        {
            var x= categoryRepository.TGet(id);
            x.CategoryStatus = false;
            categoryRepository.TUpdate(x);
            return RedirectToAction("Index");
        }
    }
}

GroceryProject/GroceryProject/Views/Category/AddCategory.cshtml
@model GroceryProject.Models.Category
@{
    ViewData["Title"] = "AddCategory";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Add Category</h2>
<br />
<form class="form-group" asp-action="AddCategory" asp-controller="Category" method="post" enctype="multipart/form-data" >
    @Html.LabelFor(x => x.CategoryName, "Category Name")
    @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
    <span asp-validation-for="CategoryName" class="text-danger"></span>
    <br />
    <br />
    @Html.LabelFor(x => x.CategoryDescription, "Category Description")
    @Html.TextBoxFor(x => x.CategoryDescription, new { @class = "form-control" })
    <span asp-validation-for="CategoryDescription" class="text-danger"></span>
    <br />
    <br />
    <button class="btn btn-success">Save</button>
</form>

GroceryProject/GroceryProject/Views/Category/GetCategory.cshtml
@model GroceryProject.Models.Category
@{
    ViewData["Title"] = "GetCategory";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Update Category</h2>
<br />
@using (Html.BeginForm("UpdateCategory", "Category", FormMethod.Post))
{
    @Html.LabelFor(x => x.CategoryID, "Category ID")
    @Html.TextBoxFor(x => x.CategoryID, new { @class = "form-control", @readonly = "readonly" })
    <br />
    @Html.LabelFor(x => x.CategoryName, "Category Name")
    @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CategoryDescription, "Category Description")
    @Html.TextBoxFor(x => x.CategoryDescription, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Save</button>
}

GroceryProject/GroceryProject/Views/Category/Index.cshtml
@model List<GroceryProject.Models.Category>


@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Categories</h2>
<br />
<table id="table1" class="table table-bordered">
    <thead>
        <tr>
            <th>Category ID</th>
            <th>Category Name</th>
            <th>Category Description</th>
            <th>Operations</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model.Where(x => x.CategoryStatus == true))
        {
            <tr>
                <td>@x.CategoryID</td>
                <td>@x.CategoryName</td>
                <td>@x.CategoryDescription</td>
                <td>
                    <a href="/Category/GetCategory/@x.CategoryID" class="btn btn-warning">Update</a>
                    @Html.ActionLink("Delete", "DeleteCategory", new { id = x.CategoryID }, new { @class = "btn btn-danger", onclick = "return confirm('Are You Sure?')" })
                </td>
            </tr>
        }
    </tbody>
</table>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet" />
<script>
    $('#table1').DataTable();
</script>

<br />
<a href="/Category/AddCategory/" class="btn btn-primary">Add Category</a>